// import React from 'react'
import dynamic from "next/dynamic"
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import squareRoot from 'fe2/getSquareRoot'
// import Header from 'fe1/header'

// const Header = (await import('fe1/header')).default
// const squareRoot = (await import('fe2/squareRoot')).default
// const Header = React.lazy(() => import('fe1/header'))
// const squareRoot = React.lazy(() => import('fe2/getSquareRoot'))
// next的ssr不支持模块联邦的ssr 所以设置false ，目前只有 @module-federation/nextjs-mf  付费支持ssr
// const Header = dynamic(() => import("fe1/header"), { ssr: false })
const HeaderWrap = dynamic(() => import("fe2/headerWrap"), { ssr: false })
// const getSquareRoot = dynamic(() => import("fe2/squareRoot"), {ssr: false })

// console.log(Header)
// console.log(getSquareRoot)


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/*<Header name='duuliy333' />*/}
        <HeaderWrap name='duuliy333' />
      <main className={styles.main}>
        <h1 className={styles.title}>
          {/*Square root of 4: {getSquareRoot({ number:4})}*/}
        </h1>


      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
